"""relations with ref fix-2

Revision ID: 574eb2eb5fe4
Revises: ab7d8d8e0c4f
Create Date: 2025-08-20 23:54:48.485599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574eb2eb5fe4'
down_revision: Union[str, Sequence[str], None] = 'ab7d8d8e0c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_referral_id'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'referrals', ['referral_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_referral_id'), 'users', 'referrals', ['referral_id'], ['id'])
    # ### end Alembic commands ###
