"""user-referral-renamed

Revision ID: 87100a93a30e
Revises: d4f44a527c82
Create Date: 2025-08-20 15:38:42.562240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87100a93a30e'
down_revision: Union[str, Sequence[str], None] = 'd4f44a527c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'unique_code')
    op.drop_column('users', 'referral_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_link', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invites', sa.Column('unique_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
