"""unique code for invite

Revision ID: 9a5ac7a9c98e
Revises: 29c3d8b28de5
Create Date: 2025-08-19 14:31:15.597302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5ac7a9c98e'
down_revision: Union[str, Sequence[str], None] = '29c3d8b28de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('unique_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'unique_code')
    # ### end Alembic commands ###
